"""Deterministic contracts and planners for source-backed creative composition."""

from .autopilot import AUTOPILOT_REQUIRED_CAPABILITIES, plan_creative_autopilot
from .autopilot_models import (
    AutopilotAbstention,
    AutopilotPolicy,
    AutopilotRequest,
    AutopilotResult,
    PlannerCapability,
)
from .errors import CreativeContractError
from .compiler import ALLOWED_COMPILE_TARGETS, COMPILE_TARGET_OPERATIONS, compile_composition_plan
from .composition import plan_composition
from .composition_models import (
    AudioMixTrack,
    CaptionPlan,
    CompiledComposition,
    CompositionApproval,
    CompositionIntent,
    CompositionPlan,
    CompositionPreview,
    GraphicElement,
    LayoutSpec,
    OutputArtifact,
    OutputVariant,
    SourceBinding,
    TimelineSegment,
)
from .manifest import build_project_manifest, select_assets
from .models import (
    AssetRights,
    AssetSelection,
    BrandConstraints,
    CreativeAsset,
    ProjectManifest,
    QualityFinding,
    RoleCandidate,
    SelectionAbstention,
    SelectionEvidence,
    SelectionIntent,
    SelectionPlan,
    SemanticSpan,
)
from .preview import bind_composition_approval, build_composition_preview
from .verification_models import (
    AttributionEvidence,
    AudioObservation,
    BrandingObservation,
    CompositionVerificationCheck,
    CompositionVerificationReport,
    OutputPackageEvidence,
    TextObservation,
    TimelineObservation,
    VerificationEvidence,
)
from .verifier import verify_composition

__all__ = [
    "ALLOWED_COMPILE_TARGETS",
    "AUTOPILOT_REQUIRED_CAPABILITIES",
    "COMPILE_TARGET_OPERATIONS",
    "AssetRights",
    "AssetSelection",
    "AttributionEvidence",
    "AudioMixTrack",
    "AudioObservation",
    "AutopilotAbstention",
    "AutopilotPolicy",
    "AutopilotRequest",
    "AutopilotResult",
    "BrandConstraints",
    "BrandingObservation",
    "CaptionPlan",
    "CompiledComposition",
    "CompositionApproval",
    "CompositionIntent",
    "CompositionPlan",
    "CompositionPreview",
    "CompositionVerificationCheck",
    "CompositionVerificationReport",
    "CreativeAsset",
    "CreativeContractError",
    "GraphicElement",
    "LayoutSpec",
    "OutputArtifact",
    "OutputPackageEvidence",
    "OutputVariant",
    "PlannerCapability",
    "ProjectManifest",
    "QualityFinding",
    "RoleCandidate",
    "SelectionAbstention",
    "SelectionEvidence",
    "SelectionIntent",
    "SelectionPlan",
    "SemanticSpan",
    "SourceBinding",
    "TextObservation",
    "TimelineObservation",
    "TimelineSegment",
    "VerificationEvidence",
    "bind_composition_approval",
    "build_composition_preview",
    "build_project_manifest",
    "compile_composition_plan",
    "plan_composition",
    "plan_creative_autopilot",
    "select_assets",
    "verify_composition",
]
