"""Public pure APIs for explicit, fake-only remote execution contracts."""

from .contracts import (
    EgressFile,
    EgressManifest,
    Money,
    NetworkApproval,
    ProviderLocation,
    RemoteContractError,
    RetentionPolicy,
    approve_egress,
    assert_network_approval,
    plan_egress,
    redact_credentials,
    validate_egress_approval,
)
from .adapters import (
    DeliveryProviderAdapter,
    FakeDeliveryAdapter,
    FakeHostingAdapter,
    FakeRenderAdapter,
    HostingProviderAdapter,
    ProviderAdapter,
    RenderProviderAdapter,
    prepare_remote_job,
    select_execution,
)
from .api import (
    create_fake_remote_receipt,
    map_fake_remote_job,
    plan_delivery,
    plan_hosting,
    verify_local_promotion,
)
from .jobs import (
    AdapterMapping,
    ApprovedLocalPlan,
    DeletionRecord,
    DownloadedArtifact,
    LocalArtifactVerification,
    PromotionReceipt,
    RemoteExecutionSelection,
    RemoteJobReceipt,
    RemoteJobSpec,
    promote_downloaded_artifact,
)

__all__ = [
    "AdapterMapping",
    "ApprovedLocalPlan",
    "DeletionRecord",
    "DeliveryProviderAdapter",
    "DownloadedArtifact",
    "EgressFile",
    "EgressManifest",
    "FakeDeliveryAdapter",
    "FakeHostingAdapter",
    "FakeRenderAdapter",
    "HostingProviderAdapter",
    "LocalArtifactVerification",
    "Money",
    "NetworkApproval",
    "PromotionReceipt",
    "ProviderAdapter",
    "ProviderLocation",
    "RemoteContractError",
    "RemoteExecutionSelection",
    "RemoteJobReceipt",
    "RemoteJobSpec",
    "RenderProviderAdapter",
    "RetentionPolicy",
    "approve_egress",
    "assert_network_approval",
    "create_fake_remote_receipt",
    "map_fake_remote_job",
    "plan_delivery",
    "plan_egress",
    "plan_hosting",
    "prepare_remote_job",
    "promote_downloaded_artifact",
    "redact_credentials",
    "select_execution",
    "validate_egress_approval",
    "verify_local_promotion",
]
