"""Resource limits and validation constants for Kinocut."""

# Video limits
MAX_VIDEO_DURATION = 14400  # 4 hours in seconds
MAX_RESOLUTION = 7680  # 8K width/height
MAX_FILE_SIZE_MB = 4096  # 4 GB
YOUTUBE_SHORTS_MAX_DURATION_SECONDS = 180.0
INSTAGRAM_REELS_MAX_DURATION_SECONDS = 90.0
MIN_SHORTS_PREVIEW_DURATION_SECONDS = 1.0

# Processing limits
DEFAULT_FFMPEG_TIMEOUT = 600  # 10 minutes
DEFAULT_AI_TIMEOUT = 3600  # 1 hour for AI operations (demucs, whisper, etc.)
DOCTOR_COMMAND_TIMEOUT = 10  # Short version/probe commands should not hang
FFPROBE_TIMEOUT = 30  # Metadata probes should fail quickly
QUALITY_GUARDRAILS_TIMEOUT = 120  # Quality check commands
MAX_BATCH_SIZE = 50
MAX_EXPORT_FRAMES_FPS = 60
MAX_AI_SCENE_FRAMES = 600
MAX_AI_UPSCALE_FRAMES = 1800
MAX_MOGRAPH_FRAMES = 1800
MAX_TEMPORAL_INSPECTION_FRAMES = 18000
MAX_INSPECTION_LINEAGE_JSON_BYTES = 65_536
MAX_INSPECTION_DECLARED_REGIONS = 32
MAX_WAVE3_JSON_BYTES = 65_536
MAX_WAVE3_VERDICT_IDS = 64
MAX_WAVE3_AUTH_DECISION_IDS = 64
MAX_ACCEPTANCE_EVIDENCE_FILES = 64

# Audio limits
MAX_AUDIO_DURATION = 3600  # 1 hour
MAX_AI_TRANSCRIBE_DURATION = MAX_AUDIO_DURATION
MIN_FREQUENCY = 20  # Human hearing lower bound
MAX_FREQUENCY = 20000  # Human hearing upper bound
MIN_SAMPLE_RATE = 8000
MAX_SAMPLE_RATE = 96000

# Numeric parameter bounds
MIN_SPEED_FACTOR = 0.01
MIN_AUDIO_BED_LOOP_CROSSFADE_SECONDS = 0.0
MAX_AUDIO_BED_LOOP_CROSSFADE_SECONDS = 30.0
MIN_AUDIO_BED_FADE_SECONDS = 0.0
MAX_AUDIO_BED_FADE_SECONDS = 30.0
MIN_AUDIO_BED_TARGET_LUFS = -70.0
MAX_AUDIO_BED_TARGET_LUFS = -5.0
MIN_AUDIO_BED_DUCK_THRESHOLD = 0.001
MAX_AUDIO_BED_DUCK_THRESHOLD = 1.0
MIN_AUDIO_BED_DUCK_RATIO = 1.0
MAX_AUDIO_BED_DUCK_RATIO = 20.0
MIN_AUDIO_BED_DUCK_ATTACK_MS = 1.0
MAX_AUDIO_BED_DUCK_ATTACK_MS = 2000.0
MIN_AUDIO_BED_DUCK_RELEASE_MS = 1.0
MAX_AUDIO_BED_DUCK_RELEASE_MS = 9000.0
MIN_AUDIO_BED_MUSIC_VOLUME = 0.0
MAX_AUDIO_BED_MUSIC_VOLUME = 2.0
MIN_AUDIO_BED_DURATION_TOLERANCE_SECONDS = 0.0
MAX_AUDIO_BED_DURATION_TOLERANCE_SECONDS = 30.0
MAX_SPEED_FACTOR = 100.0

# Encoding parameter bounds
MAX_CRF = 51
MIN_CRF = 0
DEFAULT_CRF = 23
DEFAULT_PRESET = "fast"

# Network / concurrency bounds
MAX_PORT = 65535
MIN_PORT = 1
MAX_CONCURRENCY = 16

# Processing bounds
MAX_SPEED_CHAIN_COUNT = 20

# Workflow-engine bounds (fail closed above these)
MAX_WORKFLOW_STEPS = 64
MAX_WORKFLOW_VARIANTS = 32

# Graphics composition bounds (receipt-bound editor layer stack).
MAX_GRAPHICS_LAYERS = 32
MAX_GRAPHICS_CANVAS_DURATION = 60.0  # seconds; protects the receipt output window
