"""``kinocut_sound`` — standalone audio-play production contracts.

The foundation leaf (S1) of the Sonic World audio-play production design.
This package ships **inside** the Kinocut repository but is fully usable
without importing any ``kinocut`` runtime module: it re-implements the
canonical-record pattern (frozen Pydantic models, fail-closed typed ids,
sorted-key JSON digests) so the sidecar boundary stays clean.

Public surface (this leaf):

* :class:`SoundPlan` and supporting provenance refs.
* :class:`Timeline`, :class:`Cue`, :class:`CueKind`.
* :class:`AudioFormat` and closed enums for layout/sample/time-base/dither.
* :class:`Routing`, :class:`Track`, :class:`Bus`, sends, sidechains, automation.
* :class:`Line`, :class:`ProfileRef`, :class:`Prosody`, :class:`Emotion`.
* :class:`DeliveryPolicy`, :class:`DeliveryPreset`, loudness and stem policy.
* :class:`ConsentGrant`, :class:`ConsentScope`, :class:`CloudEgressGrant`.
* :class:`AdapterDescriptor`, :class:`CapabilityResult`, :class:`CostDisclosure`.
* :class:`SoundReceipt`, :class:`SoundReceiptSection`, :class:`OrderedInput`.
* :class:`RenderFingerprint`, :class:`DeterminismClass`.
* :class:`SoundContractError` and the stable contract error codes.

Numerical defaults (loudness tolerance, true-peak ceilings, latency residual,
gap tolerance) live in :mod:`kinocut_sound.defaults`; resource ceilings
(stem-recombination tolerance, max loudness tolerance, latency residual) live
in :mod:`kinocut_sound.limits`; and closed validation regexes/sets live in
:mod:`kinocut_sound.validation`. Adapter authors import these directly rather
than reaching into owning modules.
"""

from __future__ import annotations

from kinocut_sound._canonical import (
    BoundedCode as BoundedCode,
    FrozenModel as FrozenModel,
    RecordBase as RecordBase,
    Sha256 as Sha256,
    canonical_digest as canonical_digest,
    canonical_record_id as canonical_record_id,
    location_violation as location_violation,
)
from kinocut_sound._errors import (
    INVALID_RECORD as INVALID_RECORD,
    UNSAFE_LOCATION as UNSAFE_LOCATION,
    UNKNOWN_RECORD_FIELD as UNKNOWN_RECORD_FIELD,
    SoundContractError as SoundContractError,
    contract_error as contract_error,
)
from kinocut_sound.defaults import (
    DEFAULT_ADAPTER_TIMEOUT_SECONDS as DEFAULT_ADAPTER_TIMEOUT_SECONDS,
    DEFAULT_BROADCAST_TRUE_PEAK_DBTP as DEFAULT_BROADCAST_TRUE_PEAK_DBTP,
    DEFAULT_BUS_GAIN_DB as DEFAULT_BUS_GAIN_DB,
    DEFAULT_GAP_TOLERANCE_SECONDS as DEFAULT_GAP_TOLERANCE_SECONDS,
    DEFAULT_LATENCY_RESIDUAL_SAMPLES as DEFAULT_LATENCY_RESIDUAL_SAMPLES,
    DEFAULT_LOUDNESS_TOLERANCE_LU as DEFAULT_LOUDNESS_TOLERANCE_LU,
    DEFAULT_PAN_POSITION as DEFAULT_PAN_POSITION,
    DEFAULT_PROSODY_EMPHASIS as DEFAULT_PROSODY_EMPHASIS,
    DEFAULT_PROSODY_PITCH_SEMITONES as DEFAULT_PROSODY_PITCH_SEMITONES,
    DEFAULT_PROSODY_RATE as DEFAULT_PROSODY_RATE,
    DEFAULT_PROSODY_VOLUME_DB as DEFAULT_PROSODY_VOLUME_DB,
    DEFAULT_SEND_GAIN_DB as DEFAULT_SEND_GAIN_DB,
    DEFAULT_STREAM_PODCAST_TRUE_PEAK_DBTP as DEFAULT_STREAM_PODCAST_TRUE_PEAK_DBTP,
    DEFAULT_TAIL_SECONDS as DEFAULT_TAIL_SECONDS,
)
from kinocut_sound.limits import (
    MAX_ADAPTER_TIMEOUT_SECONDS as MAX_ADAPTER_TIMEOUT_SECONDS,
    MAX_DUCKING_ATTACK_MS as MAX_DUCKING_ATTACK_MS,
    MAX_DUCKING_ATTENUATION_DB as MAX_DUCKING_ATTENUATION_DB,
    MAX_DUCKING_RECOVERY_MS as MAX_DUCKING_RECOVERY_MS,
    MAX_DUCKING_RELEASE_MS as MAX_DUCKING_RELEASE_MS,
    MAX_GAIN_DB as MAX_GAIN_DB,
    MAX_LATENCY_RESIDUAL_SAMPLES as MAX_LATENCY_RESIDUAL_SAMPLES,
    MAX_LOUDNESS_LUFS as MAX_LOUDNESS_LUFS,
    MAX_LOUDNESS_RANGE_LU as MAX_LOUDNESS_RANGE_LU,
    MAX_LOUDNESS_TOLERANCE_LU as MAX_LOUDNESS_TOLERANCE_LU,
    MAX_NORMALIZED_LEVEL as MAX_NORMALIZED_LEVEL,
    MAX_PAN_POSITION as MAX_PAN_POSITION,
    MAX_PROSODY_PITCH_SEMITONES as MAX_PROSODY_PITCH_SEMITONES,
    MAX_PROSODY_RATE as MAX_PROSODY_RATE,
    MAX_PROSODY_VOLUME_DB as MAX_PROSODY_VOLUME_DB,
    MAX_SCRIPT_ACTORS as MAX_SCRIPT_ACTORS,
    MAX_SCRIPT_BEATS_PER_SCENE as MAX_SCRIPT_BEATS_PER_SCENE,
    MAX_SCRIPT_EVENTS_PER_SCENE as MAX_SCRIPT_EVENTS_PER_SCENE,
    MAX_SCRIPT_LINES_PER_SCENE as MAX_SCRIPT_LINES_PER_SCENE,
    MAX_SCRIPT_SCENES as MAX_SCRIPT_SCENES,
    MAX_SCRIPT_TEXT_LENGTH_CHARS as MAX_SCRIPT_TEXT_LENGTH_CHARS,
    MAX_SCRIPT_TURNS_PER_SCENE as MAX_SCRIPT_TURNS_PER_SCENE,
    MAX_STEM_RECOMBINATION_TOLERANCE_LSB_24BIT as MAX_STEM_RECOMBINATION_TOLERANCE_LSB_24BIT,
    MAX_TRUE_PEAK_DBTP as MAX_TRUE_PEAK_DBTP,
    MIN_COST_USD as MIN_COST_USD,
    MIN_DUCKING_ATTENUATION_DB as MIN_DUCKING_ATTENUATION_DB,
    MIN_DUCKING_TIME_MS as MIN_DUCKING_TIME_MS,
    MIN_GAIN_DB as MIN_GAIN_DB,
    MIN_LATENCY_RESIDUAL_SAMPLES as MIN_LATENCY_RESIDUAL_SAMPLES,
    MIN_LOUDNESS_RANGE_LU as MIN_LOUDNESS_RANGE_LU,
    MIN_LOUDNESS_TOLERANCE_LU as MIN_LOUDNESS_TOLERANCE_LU,
    MIN_NORMALIZED_LEVEL as MIN_NORMALIZED_LEVEL,
    MIN_PAN_POSITION as MIN_PAN_POSITION,
    MIN_PROSODY_PITCH_SEMITONES as MIN_PROSODY_PITCH_SEMITONES,
    MIN_PROSODY_RATE as MIN_PROSODY_RATE,
    MIN_PROSODY_VOLUME_DB as MIN_PROSODY_VOLUME_DB,
    MIN_RETENTION_DAYS as MIN_RETENTION_DAYS,
    MIN_SAMPLE_RATE_HZ as MIN_SAMPLE_RATE_HZ,
    MIN_STEM_RECOMBINATION_TOLERANCE_LSB_24BIT as MIN_STEM_RECOMBINATION_TOLERANCE_LSB_24BIT,
    MIN_TEXT_LENGTH_CHARS as MIN_TEXT_LENGTH_CHARS,
    MIN_TIME_SECONDS as MIN_TIME_SECONDS,
    MIN_VERSION as MIN_VERSION,
)
from kinocut_sound.validation import (
    ADAPTER_KINDS as ADAPTER_KINDS,
    ADVISORY_RE as ADVISORY_RE,
    CODE_RE as CODE_RE,
    CREATED_BY_PATTERN as CREATED_BY_PATTERN,
    DETERMINISM_CLASSES as DETERMINISM_CLASSES,
    INFORMATIONAL_FIELDS as INFORMATIONAL_FIELDS,
    ISO8601_RE as ISO8601_RE,
    LOCALE_RE as LOCALE_RE,
    RECORD_KIND_PATTERN as RECORD_KIND_PATTERN,
    REGION_RE as REGION_RE,
    SCHEME_RE as SCHEME_RE,
    SHA256_PATTERN as SHA256_PATTERN,
    TERRITORY_RE as TERRITORY_RE,
)
from kinocut_sound.capability import (
    AdapterDescriptor as AdapterDescriptor,
    AdapterLocality as AdapterLocality,
    CapabilityResult as CapabilityResult,
    CostDisclosure as CostDisclosure,
)
from kinocut_sound.consent import (
    AuditEvent as AuditEvent,
    BlendAuthorization as BlendAuthorization,
    CloudEgressGrant as CloudEgressGrant,
    ConsentGrant as ConsentGrant,
    ConsentScope as ConsentScope,
    ConsentState as ConsentState,
    RetentionPolicy as RetentionPolicy,
)
from kinocut_sound.delivery import (
    DEFAULT_PRESET as DEFAULT_PRESET,
    DeliveryPolicy as DeliveryPolicy,
    DeliveryPreset as DeliveryPreset,
    LoudnessTarget as LoudnessTarget,
    StemLayout as StemLayout,
    StemRecombinationPolicy as StemRecombinationPolicy,
)
from kinocut_sound.format import (
    CHANNEL_COUNT as CHANNEL_COUNT,
    AudioFormat as AudioFormat,
    ChannelLayout as ChannelLayout,
    ConversionPolicy as ConversionPolicy,
    DitherPolicy as DitherPolicy,
    SampleFormat as SampleFormat,
    TimeBase as TimeBase,
)
from kinocut_sound.lines import (
    Emotion as Emotion,
    Line as Line,
    ProfileRef as ProfileRef,
    PronunciationOverride as PronunciationOverride,
    Prosody as Prosody,
)
from kinocut_sound.receipt import (
    LoudnessVerification as LoudnessVerification,
    OrderedInput as OrderedInput,
    PreservationProof as PreservationProof,
    PreservationVerdict as PreservationVerdict,
    SoundReceipt as SoundReceipt,
    SoundReceiptSection as SoundReceiptSection,
    Transformation as Transformation,
)
from kinocut_sound.render_fingerprint import (
    DeterminismClass as DeterminismClass,
    FingerprintComponent as FingerprintComponent,
    RenderFingerprint as RenderFingerprint,
    ToolchainVersion as ToolchainVersion,
)
from kinocut_sound.routing import (
    AutomationEnvelope as AutomationEnvelope,
    AutomationPoint as AutomationPoint,
    Bus as Bus,
    DuckingSidechain as DuckingSidechain,
    LatencyCompensation as LatencyCompensation,
    PanLaw as PanLaw,
    Routing as Routing,
    SendReturn as SendReturn,
    Track as Track,
)
from kinocut_sound.sound_plan import (
    AssetLicenseRef as AssetLicenseRef,
    ModelRef as ModelRef,
    PlanProvenance as PlanProvenance,
    ProcessingPresetRef as ProcessingPresetRef,
    SoundPlan as SoundPlan,
)
from kinocut_sound.timeline import (
    Cue as Cue,
    CueKind as CueKind,
    Timeline as Timeline,
)

__version__ = "0.1.0"

__all__ = [
    "ADAPTER_KINDS",
    "ADVISORY_RE",
    "CHANNEL_COUNT",
    "CODE_RE",
    "CREATED_BY_PATTERN",
    "DEFAULT_ADAPTER_TIMEOUT_SECONDS",
    "DEFAULT_BROADCAST_TRUE_PEAK_DBTP",
    "DEFAULT_BUS_GAIN_DB",
    "DEFAULT_GAP_TOLERANCE_SECONDS",
    "DEFAULT_LATENCY_RESIDUAL_SAMPLES",
    "DEFAULT_LOUDNESS_TOLERANCE_LU",
    "DEFAULT_PAN_POSITION",
    "DEFAULT_PRESET",
    "DEFAULT_PROSODY_EMPHASIS",
    "DEFAULT_PROSODY_PITCH_SEMITONES",
    "DEFAULT_PROSODY_RATE",
    "DEFAULT_PROSODY_VOLUME_DB",
    "DEFAULT_SEND_GAIN_DB",
    "DEFAULT_STREAM_PODCAST_TRUE_PEAK_DBTP",
    "DEFAULT_TAIL_SECONDS",
    "DETERMINISM_CLASSES",
    "INFORMATIONAL_FIELDS",
    "INVALID_RECORD",
    "ISO8601_RE",
    "LOCALE_RE",
    "MAX_ADAPTER_TIMEOUT_SECONDS",
    "MAX_DUCKING_ATTACK_MS",
    "MAX_DUCKING_ATTENUATION_DB",
    "MAX_DUCKING_RECOVERY_MS",
    "MAX_DUCKING_RELEASE_MS",
    "MAX_GAIN_DB",
    "MAX_LATENCY_RESIDUAL_SAMPLES",
    "MAX_LOUDNESS_LUFS",
    "MAX_LOUDNESS_RANGE_LU",
    "MAX_LOUDNESS_TOLERANCE_LU",
    "MAX_NORMALIZED_LEVEL",
    "MAX_PAN_POSITION",
    "MAX_PROSODY_PITCH_SEMITONES",
    "MAX_PROSODY_RATE",
    "MAX_PROSODY_VOLUME_DB",
    "MAX_SCRIPT_ACTORS",
    "MAX_SCRIPT_BEATS_PER_SCENE",
    "MAX_SCRIPT_EVENTS_PER_SCENE",
    "MAX_SCRIPT_LINES_PER_SCENE",
    "MAX_SCRIPT_SCENES",
    "MAX_SCRIPT_TEXT_LENGTH_CHARS",
    "MAX_SCRIPT_TURNS_PER_SCENE",
    "MAX_STEM_RECOMBINATION_TOLERANCE_LSB_24BIT",
    "MAX_TRUE_PEAK_DBTP",
    "MIN_COST_USD",
    "MIN_DUCKING_ATTENUATION_DB",
    "MIN_DUCKING_TIME_MS",
    "MIN_GAIN_DB",
    "MIN_LATENCY_RESIDUAL_SAMPLES",
    "MIN_LOUDNESS_RANGE_LU",
    "MIN_LOUDNESS_TOLERANCE_LU",
    "MIN_NORMALIZED_LEVEL",
    "MIN_PAN_POSITION",
    "MIN_PROSODY_PITCH_SEMITONES",
    "MIN_PROSODY_RATE",
    "MIN_PROSODY_VOLUME_DB",
    "MIN_RETENTION_DAYS",
    "MIN_SAMPLE_RATE_HZ",
    "MIN_STEM_RECOMBINATION_TOLERANCE_LSB_24BIT",
    "MIN_TEXT_LENGTH_CHARS",
    "MIN_TIME_SECONDS",
    "MIN_VERSION",
    "RECORD_KIND_PATTERN",
    "REGION_RE",
    "SCHEME_RE",
    "SHA256_PATTERN",
    "TERRITORY_RE",
    "UNKNOWN_RECORD_FIELD",
    "UNSAFE_LOCATION",
    "AdapterDescriptor",
    "AdapterLocality",
    "AssetLicenseRef",
    "AudioFormat",
    "AuditEvent",
    "AutomationEnvelope",
    "AutomationPoint",
    "BlendAuthorization",
    "BoundedCode",
    "Bus",
    "CapabilityResult",
    "ChannelLayout",
    "CloudEgressGrant",
    "ConsentGrant",
    "ConsentScope",
    "ConsentState",
    "ConversionPolicy",
    "CostDisclosure",
    "Cue",
    "CueKind",
    "DeliveryPolicy",
    "DeliveryPreset",
    "DeterminismClass",
    "DitherPolicy",
    "DuckingSidechain",
    "Emotion",
    "FingerprintComponent",
    "FrozenModel",
    "LatencyCompensation",
    "Line",
    "LoudnessTarget",
    "LoudnessVerification",
    "ModelRef",
    "OrderedInput",
    "PanLaw",
    "PlanProvenance",
    "PreservationProof",
    "PreservationVerdict",
    "ProcessingPresetRef",
    "ProfileRef",
    "PronunciationOverride",
    "Prosody",
    "RecordBase",
    "RenderFingerprint",
    "RetentionPolicy",
    "Routing",
    "SampleFormat",
    "SendReturn",
    "Sha256",
    "SoundContractError",
    "SoundPlan",
    "SoundReceipt",
    "SoundReceiptSection",
    "StemLayout",
    "StemRecombinationPolicy",
    "TimeBase",
    "Timeline",
    "ToolchainVersion",
    "Track",
    "Transformation",
    "canonical_digest",
    "canonical_record_id",
    "contract_error",
    "location_violation",
]
